[project]
name = "dlt-memory-leak"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dlt[az,postgres]==1.10.0",
    "psutil~=6.1.1",
]

[tool.poetry]
requires-poetry = ">=2.1"
package-mode = false
